# Generated by Django 3.2.5 on 2021-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
